#!/bin/bash
# This script is written by Alfio Salanitri <www.alfiosalanitri.it> and are licensed under MIT License.
# Credits: This script is inspired by https://github.com/pivpn/pivpn/blob/master/scripts/wireguard/clientSTAT.sh

# config variables
readonly CURRENT_PATH=$(pwd)
readonly CLIENTS_DIRECTORY="$CURRENT_PATH/clients"
readonly NOW=$(date +%s)

# after X minutes the clients will be considered disconnected
readonly TIMEOUT=15

# check if wireguard exists
if ! command -v wg &> /dev/null; then
	printf "Sorry, but wireguard is required. Install it with before.\n"
	exit 1;
fi
readonly WIREGUARD_CLIENTS=$(wg show wg0 dump | tail -n +2) # remove first line from list
if [ "" == "$WIREGUARD_CLIENTS" ]; then
	printf "No wireguard clients.\n"
	exit 1
fi

# check if the user type the telegram config file and that file exists
if [ ! "$1" ]; then
	printf "The config file with telegram chat id and bot token is required\n"
	exit 1
fi
if [ ! -f "$1" ]; then
	printf "This config file doesn't exists\n"
	exit 1
fi
readonly TELEGRAM_CHAT_ID=$(awk -F'=' '/^chat=/ { print $2}' $1)
readonly TELEGRAM_TOKEN=$(awk -F'=' '/^token=/ { print $2}' $1)

while IFS= read -r LINE; do
	public_key=$(awk '{ print $1 }' <<< "$LINE")
	remote_ip=$(awk '{ print $3 }' <<< "$LINE" | awk -F':' '{print $1}')
	last_seen=$(awk '{ print $5 }' <<< "$LINE")
	client_name=$(grep -R "$public_key" /etc/wireguard/keys/ | awk -F"/etc/wireguard/keys/|_pub:" '{print $2}' | sed -e 's./..g')
	client_file="$CLIENTS_DIRECTORY/$client_name.txt"

	# create the client file if not exists.
	if [ ! -f "$client_file" ]; then
		echo "offline" > $client_file
	fi	

	# setup notification variable
	send_notification="no"

	# last client status
	last_connection_status=$(cat $client_file)

	# elapsed seconds from last connection
	last_seen_seconds=$(date -d @"$last_seen" '+%s')
	
	# it the user is online
	if [ "$last_seen" -ne 0 ]; then

		# elapsed minutes from last connection
		last_seen_elapsed_minutes=$((10#$(($NOW - $last_seen_seconds)) / 60))

		# if the previous state was online and the elapsed minutes are greater than TIMEOUT, the user is offline
		if [ $last_seen_elapsed_minutes -gt $TIMEOUT ] && [ "online" == $last_connection_status ]; then
			echo "offline" > $client_file
			send_notification="disconnected"
			# if the previous state was offline and the elapsed minutes are lower than timout, the user is online
		elif [ $last_seen_elapsed_minutes -le $TIMEOUT ] && [ "offline" == $last_connection_status ]; then
			echo "online" > $client_file
			send_notification="connected"
		fi
	else
		# if the user is offline
		if [ "offline" != "$last_connection_status" ]; then
			echo "offline" > $client_file
			send_notification="disconnected"
		fi
	fi

	# send notification to telegram
	if [ "no" != "$send_notification" ]; then
		printf "The client %s is %s\n" $client_name $send_notification
		message="🐉 Wireguard: \`$client_name is $send_notification from ip address $remote_ip\`"
		curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -F chat_id=$TELEGRAM_CHAT_ID -F text="$message" -F parse_mode="MarkdownV2" > /dev/null 2>&1
	else
		printf "The client %s is %s, no notification will be sent.\n" $client_name $(cat $client_file)
	fi

done <<< "$WIREGUARD_CLIENTS"

exit 0
